version: "3.8"
networks:
    default:
        name: docker-standart-utilities
services:
    portainer:
        image: portainer/portainer
        container_name: docker-standart-utilities-portainer
        restart: always
        ports:
            - 8901:9000
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
